workspace = { members = ["tools"] }
[package]
name = "nekotatsu"
version = "1.2.1"
resolver = "2"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[features]
gui = ["dep:iced", "dep:iced_aw", "dep:rfd"]

[dependencies]
clap = { version = "4.5", features = ["derive"] }
directories = "5.0.1"
flate2 = "1.0.28"
iced = { version = "0.12.1", optional = true}
iced_aw = { version = "0.8.0", features = ["modal"], optional = true }
lazy_static = "1.4.0"
once_cell = "1.19.0"
prost = "0.12.1"
regex = "1.10.2"
reqwest = { version = "0.11.24", features = ["blocking"] }
rfd = { version = "0.14.0", optional = true}
serde = { version = "1.0.190", features = ["derive"] }
serde_json = "1.0.108"
zip = { version = "0.6.6", features = ["deflate-zlib"] }
