[package]
name = "gui"
version = "0.1.0"
resolver = "2"
edition = "2021"

[dependencies]
nekotatsu = { path = ".." }
rfd = { version = "0.14.0"}
slint = { version = "1.6.0"}
tokio = { version = "1.37.0", features = ["full"]}

[build-dependencies]
slint-build = "1.6.0"